# Usa una imagen oficial de Node
FROM node:18

# Crea carpeta de la app
WORKDIR /app

# Copia package.json y package-lock.json si existe
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el bot
COPY bot-shemale.js .

# Variables por defecto
ENV AUDIO_PATH="/audios"

# El bot se ejecuta con Node
CMD ["node", "bot-shemale.js"]